# Generated by Django 3.2.4 on 2021-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_question_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questintype',
            field=models.CharField(choices=[('short answer', 'Text'), ('Multiple choice question', 'Mcq'), ('Single choice question', 'Scq')], default='mcq', max_length=24),
            preserve_default=False,
        ),
    ]
